### ISSUE TITLE
checkTrue overstyrer failsafe

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/tfk-saksbehandling-fara-import#1]
https://github.com/telemark/tfk-saksbehandling-fara-import/blob/master/lib/setup-item.js#L7 vil returnere true på første treff og ikke plukke opp dersom manuell = true (som er failsafe om noe kræsjer)

**Comment by maccyber** [comment]
Ok, kunne sjekka om `manuell` er _true_ først, men blir vel unødig komplisert for å tjene inn to felt.

**Comment by zrrrzzt** [comment]
enig i det

**Comment by maccyber** [comment]
Rettet
